### PR TITLE
Add xml output to coverage reports

### PR DESCRIPTION
**Pull request by ciprianc**
For easier integration with jenkins

### CODE REVIEW

**Comment by andyhd** [comment]
LGTM - but do we need the HTML report any more? Jenkins renders the XML report very nicely.

**Comment by ciprianc** [comment]
Your choice. Personally I like both for different reasons:
 - XML for its settings (fail the built if a certain criteria is not met, like 90% coverage)
 - HTML for its human readability (I can click my way through the report and find out exactly which lines are not covered)

**Comment by andyhd** [comment]
The XML report does show which lines are not covered: http://ci.dsd.io/view/PostcodeInfo/job/BUILD-postcodeinfo/105/cobertura/_default_/postcodeinfo_apps_postcode_api_downloaders_ftp_download_manager_py/

**Comment by ciprianc** [comment]
It does indeed, I didn't know that. My argument for the need of HTML reports is now moot. Do you want me to remove the line that generates the htmls?

**Comment by andyhd** [comment]
:+1: I think it's redundant now

**Pull request merged**
