### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by andyhd**
Tests were complaining about `CREATE EXTENSION postgis` - this PR fixes that. Also, running tests now generates some coverage reports.

### CODE REVIEW

**Comment by andyhd** [comment]
test this please

**Comment by andyhd** [comment]
test this please

**Comment by aldavidson** [comment]
Doesn't work for me - enters an endless loop saying
```
curl: (7) Failed to connect to  port 80: Connection refused
Waiting for  ...
```

I suggest splitting this into two scripts, as the 'wait for db container' functionality is only needed by Jenkins - so cut the wait_for definition and call out into a separate script (test_ci.sh ?) that then calls this script (which just runs the tests)

**Comment by andyhd** [comment]
test this please

**Comment by andyhd** [comment]
test this please

**Comment by andyhd** [comment]
test this please

**Comment by aldavidson** [comment]
(thumbsup)

**Pull request merged**
